### IMPORT LIBRARIES

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### IMPORT DATASET AND CREATE DATAFRAME

In [3]:
dataset = 'BerlinHousing4049.csv'

df = pd.read_csv(dataset)

df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_total,floors,condition,grade,built,renovated,living_area_sqft
0,221900.0,3.0,1.0,NaN,5650.0,1.0,3.0,7,1955.0,0,1340.0
1,538000.0,3.0,NaN,2570.0,7242.0,2.0,3.0,7,1951.0,1991,1690.0
2,180000.0,2.0,1.0,NaN,10000.0,1.0,3.0,6,1933.0,0,NaN
3,604000.0,4.0,3.0,1960.0,5000.0,1.0,5.0,7,1965.0,0,1360.0
4,510000.0,3.0,2.0,1680.0,8080.0,1.0,3.0,8,1987.0,0,NaN

In [8]:
df.describe(include='all').transpose()

,count,mean,std,min,25%,50%,75%,max
price,9990.0,533329.214815,376887.993684,75000.0,315000.0,445819.0,639800.0,7700000.0
bedrooms,9988.0,3.364638,0.910976,1.0,3.0,3.0,4.0,11.0
bathrooms,9990.0,2.063263,0.765275,0.5,1.5,2.0,2.5,8.0
sqft_living,9989.0,2052.985985,910.804284,380.0,1410.0,1890.0,2500.0,12050.0
sqft_total,9993.0,16041.353247,45056.410806,572.0,5425.0,7916.0,11180.0,1651359.0
floors,9999.0,1.432043,0.511869,1.0,1.0,1.0,2.0,3.5
condition,9998.0,3.446389,0.666341,1.0,3.0,3.0,4.0,5.0
grade,9999.0,7.594459,1.165901,3.0,7.0,7.0,8.0,13.0
built,9996.0,1967.267307,27.988813,1900.0,1950.0,1969.0,1990.0,2015.0
renovated,9999.0,91.642364,417.830430,0.0,0.0,0.0,0.0,2015.0
living_area_sqft,9986.0,1975.878029,672.424849,620.0,1490.0,1830.0,2340.0,5790.0

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             9990 non-null   float64
 1   bedrooms          9988 non-null   float64
 2   bathrooms         9990 non-null   float64
 3   sqft_living       9989 non-null   float64
 4   sqft_total        9993 non-null   float64
 5   floors            9999 non-null   float64
 6   condition         9998 non-null   float64
 7   grade             9999 non-null   int64
 8   built             9996 non-null   float64
 9   renovated         9999 non-null   int64
 10  living_area_sqft  9986 non-null   float64
dtypes: float64(9), int64(2)
memory usage: 859.4 KB